### ISSUE TITLE
使用compile.sh脚本返回错误代码1

### ISSUE THREAD

**Issue by kyonRay** [WeBankFinTech/weid-java-sdk#170]
## 行为
按照官方文档，使用weid-build-tools安装部署SDK，在执行如下操作时未产生结果，并返回错误代码1：

```shell
fisco-bcos@fiscobcos-VirtualBox:~/workspace/weidentity-build-tools$ ./compile.sh 
fisco-bcos@fiscobcos-VirtualBox:~/workspace/weidentity-build-tools$ echo $?
1
```

## 环境
- FISCO-BCOS 2.0.0-rc3
- Java version: openjdk version "1.8.0_212"
- WeIdentity version: latest
- Ubuntu 16.04

## 结果
经过脚本调试，发现是在第13行的语句出现了错误：
```shell
SOLC=$(which fisco-solc)
```
按照官方文档下的准备工作，下载的solidity编译器二进制文件名是 `fisco-solc-ubuntu`，建立`fisco-solc`软链接即可正常开始编译。

**Comment by chaoxinhu** [comment]
@kyonRay 收到，我们会近期修改build-tools文档
