### ISSUE TITLE
创建weId时返回错误代码100106

### ISSUE THREAD

**Issue by EasonRyu** [WeBankFinTech/weid-java-sdk#184]
1、环境：fiscobcos2.0，weid-sdk-1.3.0，jdk1.8.151；
2、区块链节点运行正常；
3、weidentity-build-tools执行compile.sh成功，执行deploy.sh成功；
4、将ca.crt   node.crt  node.key  fisco.properties   weidentity.properties   ecdsa_key  拷贝到工程resources 目录下；
5、执行注册authority issuer，在
        // create WeIdentity DID,publicKey,privateKey
        ResponseData<CreateWeIdDataResult> responseCreate = weIdService.createWeId();
这里报错，错误信息为：

createWeId result:

result:null
errorCode: 100106
errorMessage: the private key does not match the current weid.
transactionInfo:null

**Comment by chaoxinhu** [comment]
这个问题，已经在发布的WeID-build-tools的最新版（1.0.5）、WeID-Java-SDK 1.3.1里得到修复。是web3sdk的版本组合问题。
