### ISSUE TITLE
使用CredentialService.createCredential()验证Credential时返回错误提示的问题

### ISSUE THREAD

**Issue by EasonRyu** [WeBankFinTech/weid-java-sdk#241]
使用CredentialService.createCredential()验证Credential时返回错误代码code=100409, message=expire date illegal。
开发环境：jdk1.8，weid-java-sdk 1.3.2
BUG描述：
1、接口名称:com.webank.weid.rpc.CredentialService.createCredential中对于入参项目“到期日”expirationDate未作处理和特别的说明，因为该项目仍然是以“毫秒”为单位，长度为13位；而接口名称:com.webank.weid.rpc.CredentialPojoService.createCredential中对于入参项目“到期日”expirationDate是以“秒”为单位，长度为10位。这两个地方不一致。（项目“创建日issuanceDate”具有同样的问题）
2、com.webank.weid.util.CredentialUtils和com.webank.weid.util.CredentialPojoUtils中对于项目“到期日expirationDate”以及项目“创建日issuanceDate”的判断方式不一致。现在的处理方式是优先返回的“code=100409, message=expire date illegal”，而未能准确的提示出“code=100402, message=credential is expired”。

**Comment by chaoxinhu** [comment]
感谢刘工！已经提了bugfix

**Comment by chaoxinhu** [comment]
#242 is opened to address this issue

**Comment by chaoxinhu** [comment]
Will close once this is released

**Comment by chaoxinhu** [comment]
已经发布于1.4.0，close.

**Comment by EasonRyu** [comment]
收到！Thanks！
